apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: metrics-undertow-openjdk17
  labels:
    app: metrics-undertow
    version: openjdk17
spec:
  output:
    to:
      kind: ImageStreamTag
      name: metrics-undertow:openjdk17
  source:
    type: Git
    git:
      uri: https://github.com/davidecelano/openshift-java-playground.git
      ref: main
    contextDir: metrics-sample-undertow
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.openjdk17
      noCache: false
      forcePull: true
      buildArgs:
        - name: BUILDER_IMAGE
          value: registry.access.redhat.com/ubi9/openjdk-17:1.21
        - name: RUNTIME_IMAGE
          value: registry.access.redhat.com/ubi9/openjdk-17-runtime:1.21
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}