apiVersion: v1
kind: Service
metadata:
  name: metrics-tomcat
  labels:
    app: metrics-tomcat
spec:
  selector:
    app: metrics-tomcat
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
