apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-tomcat
  labels:
    app: metrics-tomcat
spec:
  selector:
    matchLabels:
      app: metrics-tomcat
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
