apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: metrics-wildfly-openjdk17
  labels:
    app: metrics-wildfly
    version: openjdk17
spec:
  output:
    to:
      kind: ImageStreamTag
      name: metrics-wildfly:openjdk17
  source:
    type: Git
    git:
      uri: __REPO_URL__
      ref: main
    contextDir: metrics-sample-wildfly
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.openjdk17
      noCache: false
      forcePull: true
      buildArgs:
        - name: BUILDER_IMAGE
          value: registry.access.redhat.com/ubi8/openjdk-17:1.21
        - name: WILDFLY_IMAGE
          value: quay.io/wildfly/wildfly:31.0.1.Final-jdk17
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}