apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: metrics-tomcat-openjdk21
  labels:
    app: metrics-tomcat
    version: openjdk21
spec:
  output:
    to:
      kind: ImageStreamTag
      name: metrics-tomcat:openjdk21
  source:
    type: Git
    git:
      uri: https://github.com/yourorg/openshift-java-playground.git
      ref: main
    contextDir: metrics-sample-tomcat
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.openjdk21
      noCache: false
      forcePull: true
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}