apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: metrics-tomcat-openjdk11
  labels:
    app: metrics-tomcat
    version: openjdk11
spec:
  output:
    to:
      kind: ImageStreamTag
      name: metrics-tomcat:openjdk11
  source:
    type: Git
    git:
      uri: https://github.com/davidecelano/openshift-java-playground.git
      ref: main
    contextDir: metrics-sample-tomcat
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.openjdk11
      noCache: false
      forcePull: true
      buildArgs:
        - name: BUILDER_IMAGE
          value: registry.access.redhat.com/ubi8/openjdk-11:1.21
        - name: RUNTIME_BASE
          value: registry.access.redhat.com/ubi8/ubi-minimal:8.10
        - name: TOMCAT_VERSION
          value: "10.1.15"
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}