apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: metrics-springboot-openjdk21
  labels:
    app: metrics-springboot
    version: openjdk21
spec:
  output:
    to:
      kind: ImageStreamTag
      name: metrics-springboot:openjdk21
  source:
    type: Git
    git:
      uri: https://github.com/yourorg/openshift-java-playground.git
      ref: main
    contextDir: metrics-sample-springboot
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.openjdk21
      noCache: false
      forcePull: true
      buildArgs:
        - name: BUILDER_IMAGE
          value: registry.access.redhat.com/ubi9/openjdk-21:1.21
        - name: RUNTIME_IMAGE
          value: registry.access.redhat.com/ubi9/openjdk-21-runtime:1.21
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}