apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-springboot
  labels:
    app: metrics-springboot
spec:
  selector:
    matchLabels:
      app: metrics-springboot
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
